export const contributors = [
  {
    name: "Aayush Paigwar🧑🏻‍💻",
    role: "Project Maintainer",
    github: "https://github.com/aayushpaigwar",
    image: "https://github.com/aayushpaigwar.png",
  },
  {
    name: "Pawan Bhayde",
    role: "Project Maintainer",
    github: "https://github.com/pawanbhayde",
    image: "https://github.com/pawanbhayde.png",
  },
  {
    name: "Atharva Werulkar",
    role: "Project Maintainer",
    github: "https://github.com/Atharva-werulkar",
    image: "https://github.com/Atharva-werulkar.png",
  },
  {
    name: "Sahil Banswani",
    role: "Contributor",
    github: "https://github.com/sahil-banswani",
    image: "https://github.com/sahil-banswani.png",
  },
  {
    name: "Shreyash",
    role: "Contributor",
    github: "https://github.com/Shreyash2403",
    image: "https://github.com/Shreyash2403.png",
  },
  {
    name: "Aadam Shaikh",
    role: "Contributor",
    github: "https://github.com/AadamShaikh",
    image: "https://github.com/AadamShaikh.png",
  },
  {
    name: "Rahul Pradhan",
    role: "Contributor",
    github: "https://github.com/pradhan3249",
    image: "https://github.com/pradhan3249.png",
  },
  {
    name: "Piyush Bagde",
    role: "Contributor",
    github: "https://github.com/PiyushBagde",
    image: "https://github.com/PiyushBagde.png",
  },
  {
    name: "Ashmit Zanzote",
    role: "Contributor",
    github: "https://github.com/HackerX011",
    image: "https://github.com/HackerX011.png",
  },
  {
    name: "Manthan",
    role: "Contributor",
    github: "https://github.com/manthanwaghmare",
    image: "https://github.com/manthanwaghmare.png",
  },
  {
    name: "AKHILESH SIRSIKAR",
    role: "Contributor",
    github: "https://github.com/Akhi7122004",
    image: "https://github.com/Akhi7122004.png",
  },
  {
    name: "Sarang Chafekar",
    role: "Contributor",
    github: "https://github.com/Sarang095",
    image: "https://github.com/Sarang095.png",
  },
  {
    name: "Divya",
    role: "Contributor",
    github: "https://github.com/Divya-sh47git",
    image: "https://github.com/Divya-sh47git.png",
  },
  {
    name: "Abhijeet Moghe",
    role: "Contributor",
    github: "https://github.com/Abhijeet0605",
    image: "https://github.com/Abhijeet0605.png",
  },
  {
    name: "Palash",
    role: "Contributor",
    github: "https://github.com/palash2704",
    image: "https://github.com/palash2704.png",
  },
  {
    name: "Vedant Katre",
    role: "Contributor",
    github: "https://github.com/vedant5102",
    image: "https://github.com/vedant5102.png",
  },
  {
    name: "Aviral Pathak",
    role: "Contributor",
    github: "https://github.com/aviral-hub",
    image: "https://github.com/aviral-hub.png",
  },
  {
    name: "Atharva Gawali",
    role: "Contributor",
    github: "https://github.com/atharv2313",
    image: "https://github.com/atharv2313.png",
  },
  {
    name: "Vidhi Agrawal",
    role: "Contributor",
    github: "https://github.com/vidhi522",
    image: "https://github.com/vidhi522.png",
  },
  {
    name: "Yashika",
    role: "Contributor",
    github: "https://github.com/Yashikatahaliyani-03",
    image: "https://github.com/Yashikatahaliyani-03.png",
  },
  {
    name: "Dang Huu Thinh",
    role: "Contributor",
    github: "https://github.com/thinh12112001",
    image: "https://github.com/thinh12112001.png",
  },
  {
    name: "Himangi Tripathy",
    role: "Contributor",
    github: "https://github.com/H1mang1",
    image: "https://github.com/H1mang1.png",
  },
  {
    name: "Bhavesh Negi",
    role: "Contributor",
    github: "https://github.com/bhaveshnegi",
    image: "https://github.com/bhaveshnegi.png",
  },
  {
    name: "Kavitha Shanmugan",
    role: "Contributor",
    github: "https://github.com/kavithashanmugan",
    image: "https://github.com/kavithashanmugan.png",
  },
  {
    name: "Shubham Jain",
    role: "Contributor",
    github: "https://github.com/ShubhamJain-23",
    image: "https://github.com/ShubhamJain-23.png",
  },
  {
    name: "Abhinav Patra",
    role: "Contributor",
    github: "https://github.com/Abhinavpatra",
    image: "https://github.com/Abhinavpatra.png",
  },
  {
    name: "Deepanshi Gupta",
    role: "Contributor",
    github: "https://github.com/Deepanshi-Gupta",
    image: "https://github.com/Deepanshi-Gupta.png",
  },
  {
    name: "Nikhil Nandanwar",
    role: "Contributor",
    github: "https://github.com/nikhilnandanwar429",
    image: "https://github.com/nikhilnandanwar429.png",
  },
  {
    name: "Shreya Sanjay",
    role: "Contributor",
    github: "https://github.com/shreyyq",
    image: "https://github.com/shreyyq.png",
  },
  {
    name: "Iswar Kumar Sahu",
    role: "Contributor",
    github: "https://github.com/kumar1397",
    image: "https://github.com/kumar1397.png",
  },
  {
    name: "Zubin Bhaskar",
    role: "Contributor",
    github: "https://github.com/memickeymac03",
    image: "https://github.com/memickeymac03.png",
  },
  {
    name: "Akash Keote",
    role: "Contributor",
    github: "https://github.com/AkashKeote",
    image: "https://github.com/AkashKeote.png",
  },
  {
    name: "Mohammed Sohail",
    role: "Contributor",
    github: "https://github.com/msohailx",
    image: "https://github.com/msohailx.png",
  },
  {
    name: "Priyadarshan Ghosh Hazra",
    role: "Contributor",
    github: "https://github.com/priyadarshan-ghosh",
    image: "https://github.com/priyadarshan-ghosh.png",
  },
  {
    name: "Deepanshu Yadav",
    role: "Contributor",
    github: "https://github.com/DeepanshuYadav-code",
    image: "https://github.com/DeepanshuYadav-code.png",
  },

  {
    name: "Kunal choure",
    role: "Contributor",
    github: "https://github.com/KUNALCHOURE",
    image: "https://github.com/KUNALCHOURE.png",
  },
  {
    name: "T Rahul Prabhu ",
    role: "Contributor",
    github: "https://github.com/T-Rahul-prabhu-38",
    image: "https://github.com/T-Rahul-prabhu-38.png",
  },

  {
    name: "Nikhilesh Mauje",
    role: "Contributor",
    github: "https://github.com/Nikhileshmauje",
    image: "https://github.com/Nikhileshmauje.png",
  },
  {
    name: "Gamerking177",
    role: "Contributor",
    github: "https://github.com/Gamerking177",
    image: "https://github.com/Gamerking177.png",
  },
  {
    name: "Vijayalaxmi Wakode",
    role: "Contributor",
    github: "https://github.com/vijayalaxmi777",
    image: "https://github.com/vijayalaxmi777.png",
  },
  {
    name: "Soham Das",
    role: "Contributor",
    github: "https://github.com/theDevSoham",
    image: "https://github.com/theDevSoham.png",
  },
  {
    name: "ketan kumar",
    role: "Contributor",
    github: "https://github.com/Ketanop321",
    image: "https://github.com/Ketanop321.png",
  },

  {
    name: "Shariz Hussain",
    role: "Contributor",
    github: "https://github.com/SharizHussain",
    image: "https://github.com/SharizHussain.png"
  },
  {
    name: "Tushar Pamnani",
    role: "Contributor",
    github: "https://github.com/tusharpamnani",
    image: "https://github.com/tusharpamnani.png",
  },
  {
    name: "Gurdeep Singh",
    role: "Contributor",
    github: "https://github.com/Gurdeep99",
    image: "https://github.com/Gurdeep99.png",
  },
  {
    name: "Suprabhat Das",
    role: "Contributor",
    github: "https://github.com/suprabhatdas",
    image: "https://github.com/suprabhatdas.png",
  },
  {
    name: "Sai Bhaskar",
    role: "Contributor",
    github: "https://github.com/Sai2307l",
    image: "https://github.com/Sai2307l.png",
  },
  {
    name: "Kartik Jain",
    role: "Contributor",
    github: "https://github.com/Kartikk-26",
    image: "https://github.com/Kartikk-26.png",
  },
  {
  name: "Abhay Mourya",
  role: "Contributor",
  github: "https://github.com/abhay557",
  image: "https://github.com/abhay557.png",
  },
  {
    name: "Marcelo Amorim",
    role: "Contributor",
    github: "https://github.com/marceloams",
    image: "https://github.com/marceloams.png",
  },
  {
    name: "Frandel Wanjawa",
    role: "Contributor",
    github: "https://github.com/franfreezy",
    image: "https://github.com/franfreezy.png",
  },


];
