export const contributors = [
  {
    name: "Aayush Paigwar🧑🏻‍💻",
    role: "Project Maintainer",
    github: "https://github.com/aayushpaigwar",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Pawan Bhayde",
    role: "Project Maintainer",
    github: "https://github.com/pawanbhayde",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Atharva Werulkar",
    role: "Project Maintainer",
    github: "https://github.com/Atharva-werulkar",
    image: "https://avatar.iran.liara.run/public/24",
  },
   {
    name: "Tushar Pamnani",
    role: "Contributor",
    github: "https://github.com/tusharpamnani",
    image: "https://avatar.iran.liara.run/public/7",
  },
  {
    name: "Sahil Banswani",
    role: "Contributor",
    github: "https://github.com/sahil-banswani",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Gurdeep Singh",
    role: "Contributor",
    github: "https://github.com/Gurdeep99",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Shreyash",
    role: "Contributor",
    github: "https://github.com/Shreyash2403",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Aadam Shaikh",
    role: "Contributor",
    github: "https://github.com/AadamShaikh",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Rahul Pradhan",
    role: "Contributor",
    github: "https://github.com/pradhan3249",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Piyush Bagde",
    role: "Contributor",
    github: "https://github.com/PiyushBagde",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Ashmit Zanzote",
    role: "Contributor",
    github: "https://github.com/HackerX011",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Manthan",
    role: "Contributor",
    github: "https://github.com/manthanwaghmare",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "AKHILESH SIRSIKAR",
    role: "Contributor",
    github: "https://github.com/Akhi7122004",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Sarang Chafekar",
    role: "Contributor",
    github: "https://github.com/Sarang095",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Divya",
    role: "Contributor",
    github: "https://github.com/Divya-sh47git",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Abhijeet Moghe",
    role: "Contributor",
    github: "https://github.com/Abhijeet0605",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Palash",
    role: "Contributor",
    github: "https://github.com/palash2704",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Vedant Katre",
    role: "Contributor",
    github: "https://github.com/vedant5102",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Aviral Pathak",
    role: "Contributor",
    github: "https://github.com/aviral-hub",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Atharva Gawali",
    role: "Contributor",
    github: "https://github.com/atharv2313",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Vidhi Agrawal",
    role: "Contributor",
    github: "https://github.com/vidhi522",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Yashika",
    role: "Contributor",
    github: "https://github.com/Yashikatahaliyani-03",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Dang Huu Thinh",
    role: "Contributor",
    github: "https://github.com/thinh12112001",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Himangi Tripathy",
    role: "Contributor",
    github: "https://github.com/H1mang1",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Bhavesh Negi",
    role: "Contributor",
    github: "https://github.com/bhaveshnegi",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Kavitha Shanmugan",
    role: "Contributor",
    github: "https://github.com/kavithashanmugan",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Shubham Jain",
    role: "Contributor",
    github: "https://github.com/ShubhamJain-23",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Abhinav Patra",
    role: "Contributor",
    github: "https://github.com/Abhinavpatra",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Deepanshi Gupta",
    role: "Contributor",
    github: "https://github.com/Deepanshi-Gupta",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Shreya Sanjay",
    role: "Contributor",
    github: "https://github.com/shreyyq",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Iswar Kumar Sahu",
    role: "Contributor",
    github: "https://github.com/kumar1397",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Zubin Bhaskar",
    role: "Contributor",
    github: "https://github.com/memickeymac03",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Akash Keote",
    role: "Contributor",
    github: "https://github.com/AkashKeote",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Mohammed Sohail",
    role: "Contributor",
    github: "https://github.com/msohailx",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Priyadarshan Ghosh Hazra",
    role: "Contributor",
    github: "https://github.com/priyadarshan-ghosh",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Deepanshu Yadav",
    role: "Contributor",
    github: "https://github.com/DeepanshuYadav-code",
    image: "https://avatar.iran.liara.run/public/24",
  },

  {
    name: "Kunal choure",
    role: "Contributor",
    github: "https://github.com/KUNALCHOURE",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "T Rahul Prabhu ",
    role: "Contributor",
    github: "https://github.com/T-Rahul-prabhu-38",
    image: "https://avatar.iran.liara.run/public/24",
  },

  {
    name: "Nikhilesh Mauje",
    role: "Contributor",
    github: "https://github.com/Nikhileshmauje",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Gamerking177",
    role: "Contributor",
    github: "https://github.com/Gamerking177",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Vijayalaxmi Wakode",
    role: "Contributor",
    github: "https://github.com/vijayalaxmi777",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "Soham Das",
    role: "Contributor",
    github: "https://github.com/theDevSoham",
    image: "https://avatar.iran.liara.run/public/24",
  },
  {
    name: "ketan kumar",
    role: "Contributor",
    github: "https://github.com/Ketanop321",
    image: "https://avatar.iran.liara.run/public/24",
  },

  {
    name: "Sai Bhaskar",
    role: "Contributor",
    github: "https://github.com/Sai2307l",
    image: "https://avatar.iran.liara.run/public/15",
  },

];
